name: Publish Gitbook

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      update:
        description: 'Publish'
        required: true
        default: 'Publish'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v1

    - name: Gitbook Action
      uses: zanderzhao/gitbook-action@v1.2.4
      with:
        token: ${{ secrets.TOKEN_FOR_GITBOOK }}
        time_zone: Asia/Seoul      # set time zone
        source_dir: source         # clone from source
        source_branch: main
        source_edit_time: true     # source time
        publish_commit_message: ${{ github.event.head_commit.message }}  # use last commit message
